# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 05:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetNum', models.CharField(db_index=True, max_length=45)),
                ('acquisitionDate', models.DateField(auto_now_add=True)),
                ('assetName', models.CharField(max_length=45)),
                ('standard', models.CharField(max_length=45)),
                ('acquisitionCost', models.IntegerField()),
                ('purchaseLocation', models.CharField(max_length=45)),
                ('maintenanceYear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manageNum', models.CharField(max_length=45)),
                ('manageSpec', models.CharField(max_length=45)),
                ('size', models.IntegerField()),
                ('location', models.CharField(max_length=45)),
                ('assetInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manageNum', models.CharField(max_length=45)),
                ('manageSpec', models.CharField(max_length=45)),
                ('isInRack', models.BooleanField(default=1)),
                ('size', models.IntegerField()),
                ('location', models.CharField(max_length=45)),
                ('core', models.IntegerField()),
                ('IP', models.IntegerField(null=True)),
                ('serviceOn', models.BooleanField(default=1)),
                ('assetInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='ServerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rackLocation', models.IntegerField(null=True)),
                ('realLocation', models.CharField(max_length=45, null=True)),
                ('rack_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbApp.Rack')),
                ('server_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Server')),
            ],
        ),
        migrations.CreateModel(
            name='ServerService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alloclDate', models.DateField(auto_now_add=True)),
                ('Use', models.BooleanField(default=1)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Server')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=45)),
                ('makeDate', models.DateField()),
                ('color', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollDate', models.DateField()),
                ('diskSpec', models.FloatField()),
                ('allocUnitSize', models.FloatField()),
                ('Vol', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StorageAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manageNum', models.CharField(max_length=45)),
                ('manageSpec', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('storageForm', models.IntegerField()),
                ('assetInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='StorageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocSize', models.FloatField()),
                ('usage', models.CharField(max_length=45)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Service')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Storage')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manageNum', models.CharField(max_length=45)),
                ('manageSpec', models.CharField(max_length=45)),
                ('isInRack', models.BooleanField(default=1)),
                ('size', models.IntegerField()),
                ('IP', models.IntegerField(null=True)),
                ('serviceOn', models.BooleanField(default=1)),
                ('assetInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rackLocation', models.IntegerField(null=True)),
                ('realLocation', models.CharField(max_length=45, null=True)),
                ('rack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbApp.Rack')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Switch')),
            ],
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant', models.IntegerField()),
                ('serviceName', models.CharField(max_length=45)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='storage',
            name='storageAsset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.StorageAsset'),
        ),
        migrations.AddField(
            model_name='serverservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Service'),
        ),
    ]
