# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageasset',
            name='storageForm',
            field=models.CharField(max_length=45),
        ),
    ]
