# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0002_auto_20170402_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='location',
        ),
        migrations.RemoveField(
            model_name='server',
            name='serviceOn',
        ),
    ]
