# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0003_auto_20170402_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='IP',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='IP',
        ),
        migrations.AddField(
            model_name='server',
            name='ip',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='switch',
            name='ip',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
