# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0004_auto_20170402_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='location',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='ip',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
