# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0008_auto_20170402_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchlocation',
            name='switch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='dbApp.Switch'),
        ),
    ]
