# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0009_auto_20170402_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlocation',
            name='rack_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locationRack', to='dbApp.Rack'),
        ),
    ]
