# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0009_auto_20170402_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='color',
            field=models.CharField(max_length=10),
        ),
    ]
