# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0010_auto_20170407_1527'),
        ('dbApp', '0010_auto_20170407_0130'),
    ]

    operations = [
    ]
