# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0011_merge_20170409_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='storageAssetName',
            field=models.CharField(default='', max_length=45),
        ),
    ]
