# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0012_storage_storageassetname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverservice',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ss_server', to='dbApp.Server'),
        ),
        migrations.AlterField(
            model_name='serverservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ss_service', to='dbApp.Service'),
        ),
    ]
