# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0013_auto_20170409_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='acquisitionDate',
            field=models.DateField(),
        ),
    ]
