# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0015_auto_20170409_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='color',
            field=models.CharField(max_length=11),
        ),
    ]
